Repository BongBong-E-Bong/BBEB, pull requests merged in 2023-10, with the labels that each got.

#98 ✨가위바위보 게임 구현 완료
  client/src/App.js
  client/src/image/Paper.png
  client/src/image/RPS_sample.png
  client/src/image/Rock.png
  client/src/image/Scissors.png
  client/src/image/Tetris_sample.png
  client/src/page/RPS/Box.js
  client/src/page/RPS/RPS.js
Labels: 소정

#101 ✨ 댓글 api
  client/src/component/comment.js
  client/src/emoticon/ebongticon1.png
  client/src/emoticon/ebongticon2.png
  client/src/emoticon/ebongticon3.png
  client/src/emoticon/ebongticon4.png
  client/src/emoticon/ebongticon5.png
  client/src/emoticon/ebongticon6.png
  client/src/emoticon/ebongticon7.png
  client/src/emoticon/ebongticon8.png
Labels: 수연

#103 ✨ 프로필 및 투표 사진
  client/src/image/body/eightbong.png
  client/src/image/body/eightbongCry.png
  client/src/image/body/eightbongHover.png
  client/src/image/body/fivebong.png
  client/src/image/body/fivebongHover.png
  client/src/image/body/onebong.png
  client/src/image/body/onebongCry.png
  client/src/image/body/onebongHover.png
  client/src/image/body/sevenbong.png
  client/src/image/body/sevenbongCry.png
  client/src/image/body/sevenbongHover.png
  client/src/image/body/sixbong.png
  client/src/image/body/sixbongCry.png
  client/src/image/body/sixbongHover.png
  client/src/image/body/threebong.png
  client/src/image/body/threebongCry.png
  client/src/image/body/threebongHover.png
  client/src/image/body/twobong.png
  client/src/image/body/twobongCry.png
  client/src/image/body/twobongHover.png
  client/src/page/Profile/Profile.js
  client/src/page/Ranking/Ranking.js
Labels: 수연

#105 🎨fix: #104 refactor code
  website/src/main/java/bbeb/website/dto/PostDTO.java
Labels: 희권

#108 ✨feat: #106 Add Pinned post Priority
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
  website/src/main/java/bbeb/website/service/PostService.java
Labels: 희권

#110 ✨postId에 따라 주소 입력
  client/src/App.js
  client/src/page/Board/post.js
Labels: 수연

#112 ✨게시글에 맞는 댓글 불러오기
  client/src/component/comment.js
Labels: 수연

#114 ✨ 투표 api 수정 및 전체적인 navigate
  client/src/App.js
  client/src/page/Board/post.js
  client/src/page/Main/Main.js
  client/src/page/Profile/Profile.js
  client/src/page/Ranking/Ranking.js
  client/src/page/Vote/Vote.js
Labels: 수연

#100 ✨ 게시글 작성 api 연동 수정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/component/Modal.js
  client/src/component/login.js
  client/src/image/AddPhotoAlternate.png
  client/src/image/FormatAlignCenter.png
  client/src/image/FormatAlignJustify.png
  client/src/image/FormatAlignLeft.png
  client/src/image/FormatAlignRight.png
  client/src/image/PushPin.png
  client/src/image/Search.png
  client/src/image/comment.png
  client/src/image/hit.png
  client/src/image/like.png
  client/src/image/notThumbnail.png
  client/src/image/thumbnail.png
  client/src/image/write_poto.png
  client/src/page/Board/post.js
  client/src/page/Write/Write.js
  client/src/page/Write/writeModal.js
Labels: 소정

#118 🎨 사진 수정
  client/src/component/header.js
  client/src/image/Paper.png
  client/src/image/RPS_comeputer.png
  client/src/image/Rock.png
  client/src/image/Scissors.png
  client/src/image/bong1.png
  client/src/image/bong2.png
  client/src/image/bong3.png
  client/src/image/bong5.png
  client/src/image/bong6.png
  client/src/image/bong7.png
  client/src/image/bong8.png
  client/src/page/Choice/Choice.js
  client/src/page/RPS/Box.js
  client/src/page/RPS/RPS.js
Labels: 소정

#99 ✨ 게시글 목록 레이아웃 & api
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/page/Write/writeList.js
Labels: 소정

#119 ✨ 게시글 수정 기능
  client/src/App.js
  client/src/page/Write/writeUpdate.js
Labels: 소정

#126 ✨ 형제들 프로필
  client/src/image/story3/story3b1.gif
  client/src/image/story3/story3b10.png
  client/src/image/story3/story3b11.png
  client/src/image/story3/story3b12.gif
  client/src/image/story3/story3b13.gif
  client/src/image/story3/story3b14.png
  client/src/image/story3/story3b15.gif
  client/src/image/story3/story3b16.gif
  client/src/image/story3/story3b17.gif
  client/src/image/story3/story3b18.gif
  client/src/image/story3/story3b19.png
  client/src/image/story3/story3b2.gif
  client/src/image/story3/story3b20.gif
  client/src/image/story3/story3b21.png
  client/src/image/story3/story3b22.png
  client/src/image/story3/story3b23.gif
  client/src/image/story3/story3b24.png
  client/src/image/story3/story3b25.gif
  client/src/image/story3/story3b26.png
  client/src/image/story3/story3b27.png
  client/src/image/story3/story3b28.gif
  client/src/image/story3/story3b29.gif
  client/src/image/story3/story3b3.gif
  client/src/image/story3/story3b30.gif
  client/src/image/story3/story3b31.png
  client/src/image/story3/story3b32.png
  client/src/image/story3/story3b33.png
  client/src/image/story3/story3b4.gif
  client/src/image/story3/story3b5.gif
  client/src/image/story3/story3b6.gif
  client/src/image/story3/story3b7.gif
  client/src/image/story3/story3b8.png
  client/src/image/story3/story3b9.png
  client/src/image/story6/gogle.png
  client/src/image/story6/ongnya.png
  client/src/image/story6/ring.png
  client/src/page/Profile/Eightbong.js
  client/src/page/Profile/Fivebong.js
  client/src/page/Profile/Onebong.js
  client/src/page/Profile/Sevenbong.js
  client/src/page/Profile/Sixbong.js
  client/src/page/Profile/Threebong.js
  client/src/page/Profile/Twobong.js
Labels: 수연

#127 ✨ 액세스 토큰 로컬 스토리지에서 가져오기
  client/src/component/comment.js
  client/src/component/header.js
  client/src/component/login.js
  client/src/page/Board/post.js
  client/src/page/Ranking/Ranking.js
Labels: 수연

#129 ✨네비게이트 수정
  client/src/page/Write/Write.js
  client/src/page/Write/writeList.js
Labels: 소정

#131 ✨ 배너 이미지
  client/src/image/boardBanner.png
  client/src/image/minigameBanner.png
  client/src/image/profileBanner.png
  client/src/image/rankingBanner.png
  client/src/image/voteBanner.png
  client/src/image/webtoonBanner.png
  client/src/page/Main/Main.js
Labels: 수연

#133 ✨글작성 네비게이트 수정
  client/src/page/Write/writeModal.js
Labels: 소정

#135 🐛 본인이 쓴 게시글 들어가면 write/postId로 가는 오류 해결
  client/src/page/Board/post.js
  client/src/page/Write/Write.js
  client/src/page/Write/writeList.js
  client/src/page/Write/writeUpdate.js
Labels: 소정

#139 ✨Feat/auth/#138
  website/src/main/java/bbeb/website/config/security/WebSecurityConfig.java
  website/src/main/java/bbeb/website/dto/PostDTO.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
Labels: 희권

#141 ✨feat: #140 Modify database @GeneratedValue type
  website/src/main/java/bbeb/website/domain/character/CharacterLike.java
  website/src/main/java/bbeb/website/domain/character/MainCharacter.java
  website/src/main/java/bbeb/website/domain/comment/Comment.java
  website/src/main/java/bbeb/website/domain/game/TetrisScore.java
  website/src/main/java/bbeb/website/domain/member/Member.java
  website/src/main/java/bbeb/website/domain/member/Profile.java
  website/src/main/java/bbeb/website/domain/post/Content.java
  website/src/main/java/bbeb/website/domain/post/Post.java
  website/src/main/java/bbeb/website/domain/post/PostLike.java
  website/src/main/java/bbeb/website/domain/post/PostTag.java
  website/src/main/java/bbeb/website/domain/post/PostView.java
  website/src/main/java/bbeb/website/domain/post/Tag.java
Labels: 희권

#143 ✨Feat/database/#142
  website/src/main/java/bbeb/website/domain/comment/Comment.java
  website/src/main/java/bbeb/website/domain/member/Member.java
  website/src/main/java/bbeb/website/domain/member/Profile.java
  website/src/main/java/bbeb/website/domain/post/Content.java
  website/src/main/java/bbeb/website/domain/post/Post.java
  website/src/main/java/bbeb/website/domain/post/Tag.java
Labels: 희권

#144 🐛fix: #136 Add profile path
  website/src/main/java/bbeb/website/dto/PostDTO.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
Labels: 희권

#146 ✨feat: #145 Add search my post api
  website/src/main/java/bbeb/website/controller/PostController.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
  website/src/main/java/bbeb/website/service/PostService.java
Labels: 희권
