Repository BongBong-E-Bong/BBEB, pull requests merged in 2023-08, with the labels that each got.

#22 Feature/router/#7
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/component/header.js
  client/src/index.js
  client/src/page/Main/Main.js
  client/src/page/Profile/Profile.js
Labels: 수연

#30 🐛Backend
  .github/workflows/main.yml
  scripts/start.sh
  website/build.gradle
Labels: 희권

#31 ✨Feature/auth/#16
  website/build.gradle
  website/src/main/java/bbeb/website/WebsiteApplication.java
  website/src/main/java/bbeb/website/config/SwaggerConfig.java
  website/src/main/java/bbeb/website/config/security/QuerydslConfig.java
  website/src/main/java/bbeb/website/config/security/WebSecurityConfig.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtAuthenticationFilter.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtTokenProvider.java
  website/src/main/java/bbeb/website/controller/AuthController.java
  website/src/main/java/bbeb/website/controller/MemberController.java
  website/src/main/java/bbeb/website/domain/Member.java
  website/src/main/java/bbeb/website/domain/Role.java
  website/src/main/java/bbeb/website/dto/AuthDTO.java
  website/src/main/java/bbeb/website/dto/TokenDTO.java
  website/src/main/java/bbeb/website/entity/Member.java
  website/src/main/java/bbeb/website/repository/MemberRepository.java
  website/src/main/java/bbeb/website/repository/MemberRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/MemberRepositoryImpl.java
  website/src/main/java/bbeb/website/service/AuthService.java
  website/src/main/java/bbeb/website/service/CustomMemberDetailsService.java
  website/src/main/java/bbeb/website/service/MemberService.java
Labels: 희권

#33 ✨Feature/swagger adress/#32
  .github/workflows/main.yml
  website/src/main/java/bbeb/website/config/security/WebSecurityConfig.java
Labels: 희권

#34 🎨docs: Move QuerydslConfig.java
  website/src/main/java/bbeb/website/config/QuerydslConfig.java
Labels: 희권

#37 ✨게시글 레이아웃 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/image/obong.png
  client/src/index.js
  client/src/page/Board/post.js
  client/src/page/Profile/Profile.js
  client/src/theme.js
Labels: 수연

#39 ✨Feature/exception/#38
  website/build.gradle
  website/src/main/java/bbeb/website/WebsiteApplication.java
  website/src/main/java/bbeb/website/config/exception/CustomAuthenticationEntryPoint.java
  website/src/main/java/bbeb/website/config/exception/CustomException.java
  website/src/main/java/bbeb/website/config/exception/ErrorCode.java
  website/src/main/java/bbeb/website/config/exception/ErrorResponse.java
  website/src/main/java/bbeb/website/config/exception/GlobalExceptionHandler.java
  website/src/main/java/bbeb/website/config/security/WebSecurityConfig.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtAuthenticationFilter.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtExceptionFilter.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtTokenProvider.java
  website/src/main/java/bbeb/website/controller/AuthController.java
  website/src/main/java/bbeb/website/dto/AuthDTO.java
  website/src/main/java/bbeb/website/repository/MemberRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/MemberRepositoryImpl.java
  website/src/main/java/bbeb/website/service/AuthService.java
Labels: 희권

#41 🎨36 코드 리팩토링
  client/src/component/header.js
  client/src/page/Board/post.js
  client/src/page/Profile/Profile.js
  client/src/theme.js
Labels: 수연

#44 ✨feat: #40 Add profile
  website/build.gradle
  website/image/profileImages/defaultProfile.jpg
  website/src/main/java/bbeb/website/WebsiteApplication.java
  website/src/main/java/bbeb/website/config/MultipartConfig.java
  website/src/main/java/bbeb/website/config/S3Config.java
  website/src/main/java/bbeb/website/controller/MemberController.java
  website/src/main/java/bbeb/website/domain/Member.java
  website/src/main/java/bbeb/website/domain/Profile.java
  website/src/main/java/bbeb/website/dto/ProfileDTO.java
  website/src/main/java/bbeb/website/repository/ProfileRepository.java
  website/src/main/java/bbeb/website/service/MemberService.java
Labels: 희권

#47 ✨feat: #46 Add tetris score API
  website/image/profileImages/defaultProfile.jpg
  website/src/main/java/bbeb/website/config/SwaggerConfig.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtAuthenticationFilter.java
  website/src/main/java/bbeb/website/config/security/jwt/JwtTokenProvider.java
  website/src/main/java/bbeb/website/controller/MemberController.java
  website/src/main/java/bbeb/website/controller/TetrisScoreController.java
  website/src/main/java/bbeb/website/domain/Member.java
  website/src/main/java/bbeb/website/domain/Profile.java
  website/src/main/java/bbeb/website/domain/TetrisScore.java
  website/src/main/java/bbeb/website/dto/TetrisScoreDTO.java
  website/src/main/java/bbeb/website/repository/member/MemberRepository.java
  website/src/main/java/bbeb/website/repository/member/MemberRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/member/MemberRepositoryImpl.java
  website/src/main/java/bbeb/website/repository/profile/ProfileRepository.java
  website/src/main/java/bbeb/website/repository/tetrisscore/TetrisScoreRepository.java
  website/src/main/java/bbeb/website/repository/tetrisscore/TetrisScoreRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/tetrisscore/TetrisScoreRepositoryImpl.java
  website/src/main/java/bbeb/website/service/AuthService.java
  website/src/main/java/bbeb/website/service/CustomMemberDetailsService.java
  website/src/main/java/bbeb/website/service/MemberService.java
  website/src/main/java/bbeb/website/service/TetrisScoreService.java
Labels: 희권

#45 ✨ 로그인 레이아웃 및 기능 추가
  client/src/component/authModal_fail.js
  client/src/component/authModal_success.js
  client/src/component/header.js
  client/src/component/login.js
  client/src/image/kakaologo.png
  client/src/image/login.png
  client/src/image/register.png
  client/src/page/Main/Main.js
Labels: 소정

#43 ✨댓글 컴포넌트 레이아웃 구현
  client/src/component/comment.js
  client/src/emoticon/...emoticon.png
  client/src/page/Board/post.js
Labels: 수연

#48 ✨회원가입 레이아웃 구성
  client/package-lock.json
  client/package.json
  client/src/component/register.js
  client/src/page/Main/Main.js
Labels: 소정

#62 ✨ API 연동 완료
  client/src/component/authModal_fail.js
  client/src/component/authModal_success.js
  client/src/component/header.js
  client/src/component/login.js
  client/src/component/register.js
Labels: 소정

#63 🎨 로그인 및 회원가입(+모달창) 레이아웃 수정
  client/src/component/authModal_fail.js
  client/src/component/authModal_success.js
  client/src/component/header.js
  client/src/component/login.js
  client/src/component/register.js
Labels: 소정

#64 ✨ 이봉이 형제 상세 프로필 구현
  client/src/App.js
  client/src/component/ProfileForm.js
  client/src/component/comment.js
  client/src/image/body2b.png
  client/src/image/story2/story2b1.gif
  client/src/image/story2/story2b10.png
  client/src/image/story2/story2b11.png
  client/src/image/story2/story2b12.png
  client/src/image/story2/story2b2.gif
  client/src/image/story2/story2b3.gif
  client/src/image/story2/story2b4.gif
  client/src/image/story2/story2b5.gif
  client/src/image/story2/story2b6.gif
  client/src/image/story2/story2b7.gif
  client/src/image/story2/story2b8.gif
  client/src/image/story2/story2b9.gif
  client/src/page/Profile/Eightbong.js
  client/src/page/Profile/Fivebong.js
  client/src/page/Profile/Onebong.js
  client/src/page/Profile/Sevenbong.js
  client/src/page/Profile/Sixbong.js
  client/src/page/Profile/Threebong.js
  client/src/page/Profile/Twobong.js
Labels: 수연

#65 ✨feat: #55 Add post comment
  website/src/main/java/bbeb/website/config/SwaggerConfig.java
  website/src/main/java/bbeb/website/controller/CommentController.java
  website/src/main/java/bbeb/website/domain/comment/Comment.java
  website/src/main/java/bbeb/website/domain/comment/CommentType.java
  website/src/main/java/bbeb/website/domain/member/Member.java
  website/src/main/java/bbeb/website/domain/post/Post.java
  website/src/main/java/bbeb/website/dto/CommentDTO.java
  website/src/main/java/bbeb/website/dto/PostDTO.java
  website/src/main/java/bbeb/website/repository/comment/CommentRepository.java
  website/src/main/java/bbeb/website/repository/comment/CommentRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
  website/src/main/java/bbeb/website/repository/member/ProfileRepository.java
  website/src/main/java/bbeb/website/repository/post/content/ContentRepository.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepository.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/post/post/PostRepositoryImpl.java
  website/src/main/java/bbeb/website/repository/post/postlike/PostLikeRepository.java
  website/src/main/java/bbeb/website/repository/post/postlike/PostLikeRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/post/postlike/PostLikeRepositoryImpl.java
  website/src/main/java/bbeb/website/repository/post/tag/PostTagRepository.java
  website/src/main/java/bbeb/website/repository/post/tag/PostTagRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/post/tag/PostTagRepositoryImpl.java
  website/src/main/java/bbeb/website/repository/post/tag/TagRepository.java
  website/src/main/java/bbeb/website/service/CommentService.java
  website/src/main/java/bbeb/website/service/MemberService.java
  website/src/main/java/bbeb/website/service/PostService.java
Labels: 희권

#66 ✨Feature/comment#55
  website/src/main/java/bbeb/website/domain/comment/Comment.java
  website/src/main/java/bbeb/website/domain/comment/CommentType.java
  website/src/main/java/bbeb/website/dto/CommentDTO.java
  website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
  website/src/main/java/bbeb/website/service/CommentService.java
Labels: 희권

#67 ✨feat: #57 Add vote system
  website/src/main/java/bbeb/website/config/SwaggerConfig.java
  website/src/main/java/bbeb/website/config/exception/ErrorCode.java
  website/src/main/java/bbeb/website/controller/CharacterController.java
  website/src/main/java/bbeb/website/domain/character/CharacterLike.java
  website/src/main/java/bbeb/website/domain/character/MainCharacter.java
  website/src/main/java/bbeb/website/domain/member/Member.java
  website/src/main/java/bbeb/website/dto/VoteDTO.java
  website/src/main/java/bbeb/website/repository/character/character/CharacterRepository.java
  website/src/main/java/bbeb/website/repository/character/character/CharacterRepositoryCustom.java
  website/src/main/java/bbeb/website/repository/character/character/CharacterRepositoryImpl.java
  website/src/main/java/bbeb/website/repository/character/characterlike/CharacterLikeRepository.java
  website/src/main/java/bbeb/website/service/CharacterService.java
  website/src/main/java/bbeb/website/util/scheduler/VoteScheduler.java
Labels: 희권

#68 ✨ 게시글 백엔드 통신
  client/src/page/Board/post.js
Labels: 수연

#76 ✨Feature/docs/#75
  website/src/main/java/bbeb/website/config/exception/ErrorCode.java
  website/src/main/java/bbeb/website/config/exception/ErrorResponse.java
  website/src/main/java/bbeb/website/controller/AuthController.java
  website/src/main/java/bbeb/website/controller/CharacterController.java
  website/src/main/java/bbeb/website/controller/CommentController.java
  website/src/main/java/bbeb/website/controller/MemberController.java
  website/src/main/java/bbeb/website/controller/PostController.java
  website/src/main/java/bbeb/website/controller/TetrisScoreController.java
  website/src/main/java/bbeb/website/dto/AuthDTO.java
  website/src/main/java/bbeb/website/dto/CommentDTO.java
  website/src/main/java/bbeb/website/dto/PostDTO.java
  website/src/main/java/bbeb/website/dto/ProfileDTO.java
  website/src/main/java/bbeb/website/dto/TetrisScoreDTO.java
  website/src/main/java/bbeb/website/dto/TokenDTO.java
  website/src/main/java/bbeb/website/dto/VoteDTO.java
  website/src/main/java/bbeb/website/repository/comment/CommentRepositoryImpl.java
  website/src/main/java/bbeb/website/service/AuthService.java
  website/src/main/java/bbeb/website/service/CharacterService.java
  website/src/main/java/bbeb/website/service/CommentService.java
  website/src/main/java/bbeb/website/service/MemberService.java
  website/src/main/java/bbeb/website/service/PostService.java
  website/src/main/java/bbeb/website/service/TetrisScoreService.java
Labels: 희권

#78 ✨ 인기 투표 순위 백엔드 통신
  client/src/page/Ranking/Ranking.js
Labels: 수연

#69 ✨ 인기투표 완료
  client/src/App.js
  client/src/page/Choice/Choice.js
  client/src/page/Choice/successModal.js
Labels: 소정
